from enum import StrEnum

class IMAPSearchCriteria(StrEnum):
    ALL = 'ALL'
    SEEN = 'SEEN'
    UNSEEN = 'UNSEEN'
    FLAGGED = 'FLAGGED'
    UNFLAGGED = 'UNFLAGGED'
    ANSWERED = 'ANSWERED'
    UNANSWERED = 'UNANSWERED'
    DELETED = 'DELETED'
    UNDELETED = 'UNDELETED'
    DRAFT = 'DRAFT'
    @staticmethod
    def before(date: str) -> str: ...
    @staticmethod
    def on(date: str) -> str: ...
    @staticmethod
    def since(date: str) -> str: ...
    @staticmethod
    def from_address(email: str) -> str: ...
    @staticmethod
    def to_address(email: str) -> str: ...
    @staticmethod
    def subject(subject: str) -> str: ...
    @staticmethod
    def body(text: str) -> str: ...
    @staticmethod
    def text(text: str) -> str: ...
    @staticmethod
    def header(field: str, value: str) -> str: ...
    @staticmethod
    def and_criteria(*criteria: str) -> str: ...
    @staticmethod
    def or_criteria(*criteria: str) -> str: ...
    @staticmethod
    def not_criteria(criteria: str) -> str: ...
    @staticmethod
    def recent(days: int = 7) -> str: ...
    @staticmethod
    def message_id(message_id: str) -> str: ...
    @staticmethod
    def uid(uid: str) -> str: ...
